import type { BlogPost, FaqItem, PricingPlan, Service, SiteStat, Testimonial } from "@/types/cms";
import { blogImage, serviceImage, testimonialAvatar } from "@/lib/site-images";

const ts = "2026-06-01T00:00:00.000Z";

export const FALLBACK_SERVICES: Service[] = [
  {
    id: "web-design",
    slug: "web-design",
    title: "تصميم المواقع",
    tagline: "مواقع جميلة تحوّل الزوار لعملاء.",
    shortDescription: "مواقع تركّز على التحويل بتصميم راقٍ وحركة مدروسة.",
    description: "نصمّم مواقع تبدو احترافية، سريعة، وتحوّل الزوار إلى عملاء. كل تفصيلة مدروسة — من الشبكة إلى أصغر تفاعل.",
    icon: "Globe",
    features: ["تصميم متوافق مع الهوية", "تخطيطات متجاوبة", "حركة وتفاعلات", "تكامل CMS"],
    deliverables: ["تصميم بصري متوافق مع العلامة", "تخطيطات متجاوبة", "حركة وتفاعلات دقيقة", "تسليم نظام تصميم", "بنية جاهزة لـ CMS"],
    imageUrl: serviceImage("web-design"),
    process: [
      { title: "اكتشاف", description: "ورش عمل، تحليل الجمهور والمنافسين." },
      { title: "تصميم", description: "Wireframes، شاشات عالية الدقة ونظام موثّق." },
      { title: "بناء", description: "كود جاهز للإنتاج مع أداء مدمج." },
      { title: "تحسين", description: "تحسين ما بعد الإطلاق بناءً على البيانات." },
    ],
    order: 1,
    status: "published",
    metaTitle: "تصميم المواقع — Top1Markting",
    metaDescription: "مواقع تركّز على التحويل بتصميم راقٍ وحركة مدروسة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "web-apps",
    slug: "web-apps",
    title: "تطبيقات الويب",
    tagline: "تطبيقات قابلة للتوسع. بنية نظيفة.",
    shortDescription: "تطبيقات ويب قابلة للتوسع بأحدث التقنيات وبنية نظيفة.",
    description: "من الأدوات الداخلية إلى المنصات الموجهة للعملاء — نبني تطبيقات تتوسع مع عملك وتبقى سهلة الصيانة.",
    icon: "Code2",
    features: ["React / Next.js", "واجهات برمجية آمنة", "صلاحيات ومستخدمين", "بنية Edge-ready"],
    deliverables: ["React / Next.js / TypeScript", "واجهات برمجية آمنة", "مصادقة وصلاحيات", "بنية Edge-ready", "اختبارات وCI/CD"],
    imageUrl: serviceImage("web-apps"),
    process: [
      { title: "تخطيط", description: "البنية، نمذجة البيانات، تحديد النطاق." },
      { title: "تصميم", description: "مسارات المستخدم، نماذج أولية، نظام تصميم." },
      { title: "بناء", description: "Sprints أسبوعين مع عروض أسبوعية." },
      { title: "إطلاق", description: "نشر، مراقبة، تكرار." },
    ],
    order: 2,
    status: "published",
    metaTitle: "تطبيقات الويب — Top1Markting",
    metaDescription: "تطبيقات ويب قابلة للتوسع بأحدث التقنيات وبنية نظيفة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "seo",
    slug: "seo",
    title: "تحسين SEO",
    tagline: "نمو عضوي مُهندَس.",
    shortDescription: "SEO تقني، استراتيجية محتوى ونمو عضوي قابل للقياس.",
    description: "SEO تقني واستراتيجية محتوى ونمو قابل للقياس. نحوّل البحث إلى قناة اكتساب موثوقة.",
    icon: "Search",
    features: ["تدقيق تقني", "استراتيجية محتوى", "Schema markup", "تقارير شهرية"],
    deliverables: ["تدقيق تقني", "استراتيجية كلمات مفتاحية", "Schema markup", "استراتيجية روابط", "تقارير شهرية"],
    imageUrl: serviceImage("seo"),
    process: [
      { title: "تدقيق", description: "فحص الموقع، تحديد العوائق والفرص السريعة." },
      { title: "استراتيجية", description: "Clusters كلمات مفتاحية وخارطة محتوى." },
      { title: "تنفيذ", description: "تحسينات On-page وتقنية ومحتوى." },
      { title: "قياس", description: "تقارير شهرية مرتبطة بالإيرادات." },
    ],
    order: 3,
    status: "published",
    metaTitle: "تحسين SEO — Top1Markting",
    metaDescription: "SEO تقني، استراتيجية محتوى ونمو عضوي قابل للقياس.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "ui-ux",
    slug: "ui-ux",
    title: "تصميم UI / UX",
    tagline: "واجهات يحبها المستخدمون.",
    shortDescription: "واجهات جميلة وبديهية مبنية على بحث المستخدم الحقيقي.",
    description: "تصميم مبني على البحث يجعل المنتجات المعقدة بسيطة. جميل، قابل للوصول، قابل للقياس.",
    icon: "Palette",
    features: ["بحث المستخدم", "أنظمة تصميم", "نماذج أولية", "إمكانية الوصول WCAG"],
    deliverables: ["بحث المستخدم", "هندسة المعلومات", "تصميم عالي الدقة", "نظام تصميم", "اختبار قابلية الاستخدام"],
    imageUrl: serviceImage("ui-ux"),
    process: [
      { title: "بحث", description: "مقابلات، Jobs-to-be-done، تحليل المنافسين." },
      { title: "تصميم", description: "Wireframes، نماذج أولية، شاشات نهائية." },
      { title: "تحقق", description: "اختبار قابلية الاستخدام مع مستخدمين حقيقيين." },
      { title: "تسليم", description: "نظام موثّق جاهز للتطوير." },
    ],
    order: 4,
    status: "published",
    metaTitle: "تصميم UI / UX — Top1Markting",
    metaDescription: "واجهات جميلة وبديهية مبنية على بحث المستخدم الحقيقي.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "digital-solutions",
    slug: "digital-solutions",
    title: "حلول رقمية",
    tagline: "منصات مخصصة من البداية للنهاية.",
    shortDescription: "منصات مخصصة، أتمتة وتكاملات لعملك.",
    description: "نبني منصات مخصصة وأتمتة وتكاملات تربط عملك وتزيل الاحتكاك.",
    icon: "Layers",
    features: ["أدوات داخلية", "تكاملات API", "أتمتة", "ربط CRM وERP"],
    deliverables: ["أدوات داخلية", "تكاملات API", "أتمتة سير العمل", "ربط CRM وERP", "لوحات تحكم مخصصة"],
    imageUrl: serviceImage("digital-solutions"),
    process: [
      { title: "اكتشاف", description: "رسم سير العمل ونقاط الألم." },
      { title: "تصميم", description: "بنية الحل وتجربة المستخدم." },
      { title: "بناء", description: "تسليم على مراحل." },
      { title: "دعم", description: "صيانة وتحسينات مستمرة." },
    ],
    order: 5,
    status: "published",
    metaTitle: "حلول رقمية — Top1Markting",
    metaDescription: "منصات مخصصة، أتمتة وتكاملات لعملك.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
];

const blogContent = `<h2>مقدمة</h2>
<p>هنا يبدأ المقال. في التطبيق الحقيقي، هذا المحتوى يُدار من لوحة التحكم — فريق التحرير ينشر بدون لمس الكود.</p>
<p>أسلوب Top1Markting: اكتب كأنك تشرح لصديق ذكي جديد على الموضوع.</p>
<h2>المشكلة الحقيقية</h2>
<p>كل مشروع يبدأ بسؤال: ما المشكلة الحقيقية التي نحلها؟ ليس العَرَض — السبب الجذري.</p>
<p>معظم الفرق تحسّن الشيء الخاطئ لأنها لم تتوقف لتسأل.</p>
<h2>منهجيتنا</h2>
<p>إطار من أربع خطوات: اكتشاف، تصميم، بناء، نمو. كل خطوة لها مخرجات واضحة وحلقة feedback.</p>
<h2>النتيجة</h2>
<p>عند التنفيذ الصحيح: منتج ينطلق بسرعة، يؤدي جيداً، ويستمر في النمو بعد الإطلاق.</p>
<h2>الخلاصة</h2>
<ul>
<li>ابدأ بالمشكلة الحقيقية، لا بالمطلوب السطحي.</li>
<li>الأداء قرار تصميم، ليس مرحلة أخيرة.</li>
<li>انشر بخطوات صغيرة قابلة للقياس.</li>
</ul>`;

export const FALLBACK_BLOG_POSTS: BlogPost[] = [
  {
    id: "lighthouse-99-by-default",
    slug: "lighthouse-99-by-default",
    title: "كيف نطلق مواقع Lighthouse 99 افتراضياً",
    excerpt: "الأداء ليس ميزة تُضاف في النهاية. هذا النظام الذي نستخدمه.",
    content: blogContent,
    featuredImage: blogImage("lighthouse-99-by-default"),
    featuredImageAlt: "شاشة تعرض نتائج أداء موقع ويب",
    category: "الأداء",
    tags: ["أداء", "lighthouse", "web-vitals"],
    author: "ليلى بناني",
    readTime: 6,
    views: 1240,
    trending: true,
    status: "published",
    metaTitle: "كيف نطلق مواقع Lighthouse 99 افتراضياً — Top1Markting",
    metaDescription: "الأداء ليس ميزة تُضاف في النهاية. هذا النظام الذي نستخدمه.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-06-12T00:00:00.000Z",
  },
  {
    id: "saas-seo-playbook-2026",
    slug: "saas-seo-playbook-2026",
    title: "دليل SEO عملي لشركات SaaS في 2026",
    excerpt: "انسَ الحيل. الدليل الذي ينجح في 2026 ممل، تقني، وبطيء — وهذا سره.",
    content: blogContent,
    featuredImage: blogImage("saas-seo-playbook-2026"),
    featuredImageAlt: "تحليل SEO على شاشة لابتوب",
    category: "SEO",
    tags: ["seo", "saas", "نمو"],
    author: "هناء صالح",
    readTime: 8,
    views: 980,
    trending: true,
    status: "published",
    metaTitle: "دليل SEO عملي لشركات SaaS في 2026 — Top1Markting",
    metaDescription: "انسَ الحيل. الدليل الذي ينجح في 2026 ممل، تقني، وبطيء.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-06-04T00:00:00.000Z",
  },
  {
    id: "premium-microinteractions",
    slug: "premium-microinteractions",
    title: "تصميم micro-interactions تبدو premium",
    excerpt: "لماذا المنتجات الأغلى ثمناً هي الأكثر restraint في الحركة.",
    content: blogContent,
    featuredImage: blogImage("premium-microinteractions"),
    featuredImageAlt: "تصميم واجهة مستخدم على شاشة",
    category: "UI/UX",
    tags: ["ui", "ux", "حركة"],
    author: "يوسف كرم",
    readTime: 5,
    views: 640,
    trending: false,
    status: "published",
    metaTitle: "تصميم micro-interactions تبدو premium — Top1Markting",
    metaDescription: "لماذا المنتجات الأغلى ثمناً هي الأكثر restraint في الحركة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-05-27T00:00:00.000Z",
  },
  {
    id: "design-system-foundations",
    slug: "design-system-foundations",
    title: "أساسيات نظام التصميم التي يجب أن تبدأ بها",
    excerpt: "قبل المكوّنات، قبل الـ tokens — الأساسيات التي تجعل النظام يتراكم.",
    content: blogContent,
    featuredImage: blogImage("design-system-foundations"),
    featuredImageAlt: "عينات ألوان وخطوط لنظام تصميم",
    category: "تصميم",
    tags: ["design-system", "tokens"],
    author: "عمر حديد",
    readTime: 7,
    views: 520,
    trending: false,
    status: "published",
    metaTitle: "أساسيات نظام التصميم — Top1Markting",
    metaDescription: "قبل المكوّنات، قبل الـ tokens — الأساسيات التي تجعل النظام يتراكم.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-05-18T00:00:00.000Z",
  },
  {
    id: "shipping-fast-without-debt",
    slug: "shipping-fast-without-debt",
    title: "الإطلاق السريع بدون تراكم tech debt",
    excerpt: "السرعة والجودة ليستا على طرفي نقيض إذا ضبطت الإعدادات الصحيحة.",
    content: blogContent,
    featuredImage: blogImage("shipping-fast-without-debt"),
    featuredImageAlt: "مطور يكتب كود على جهاز لابتوب",
    category: "هندسة",
    tags: ["هندسة", "tech-debt"],
    author: "ليلى بناني",
    readTime: 6,
    views: 410,
    trending: false,
    status: "published",
    metaTitle: "الإطلاق السريع بدون tech debt — Top1Markting",
    metaDescription: "السرعة والجودة ليستا على طرفي نقيض إذا ضبطت الإعدادات الصحيحة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-05-03T00:00:00.000Z",
  },
  {
    id: "from-figma-to-production",
    slug: "from-figma-to-production",
    title: "من Figma للإنتاج — دليل التسليم",
    excerpt: "Checklist الدقيق الذي نستخدمه للانتقال من التصميم للكود بدون فقدان النية.",
    content: blogContent,
    featuredImage: blogImage("from-figma-to-production"),
    featuredImageAlt: "تصميم واجهة على شاشة ولوحة مفاتيح",
    category: "عمليات",
    tags: ["figma", "handoff", "عمليات"],
    author: "عمر حديد",
    readTime: 5,
    views: 380,
    trending: false,
    status: "published",
    metaTitle: "من Figma للإنتاج — Top1Markting",
    metaDescription: "Checklist الدقيق للانتقال من التصميم للكود بدون فقدان النية.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-04-22T00:00:00.000Z",
  },
];

export const FALLBACK_TESTIMONIALS: Testimonial[] = [
  {
    id: "maya-khalil",
    name: "مايا خليل",
    role: "رئيسة النمو",
    company: "Nimbus",
    quote: "Top1Markting أعادت بناء موقعنا التسويقي وارتفع التحويل 47% في الشهر الأول. أفضل وكالة عملنا معها.",
    rating: 5,
    avatarUrl: testimonialAvatar("maya-khalil"),
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "daniel-park",
    name: "دانيال بارك",
    role: "CTO",
    company: "Helix",
    quote: "اهتمامهم بالتفاصيل لا يُصدَّق. كل تفاعل، كل pixel — مدروس. والكود نظيف مثل التصميم.",
    rating: 5,
    avatarUrl: testimonialAvatar("daniel-park"),
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "sara-el-masry",
    name: "سارة المصري",
    role: "مؤسسة",
    company: "Aperture",
    quote: "سريعون، شفافون، ومهووسون بالجودة. مدّدنا التعاقد ثلاث مرات.",
    rating: 5,
    avatarUrl: testimonialAvatar("sara-el-masry"),
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const FALLBACK_PRICING: PricingPlan[] = [
  {
    id: "launch",
    name: "إطلاق",
    price: "٤٬٩٠٠$",
    period: "/ مشروع",
    description: "مثالي لصفحات الهبوط والمواقع التسويقية الصغيرة.",
    features: ["حتى 5 صفحات", "تصميم متجاوب", "SEO أساسي", "تسليم خلال أسبوعين"],
    highlighted: false,
    ctaLabel: "ابدأ المشروع",
    ctaHref: "/contact",
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "studio",
    name: "استوديو",
    price: "١٢٬٥٠٠$",
    period: "/ مشروع",
    description: "مواقع تسويقية كاملة مع CMS وحركة متقدمة.",
    features: ["حتى 15 صفحة", "تكامل CMS", "SEO متقدم", "Analytics + GTM", "تسليم خلال 4 أسابيع"],
    highlighted: true,
    ctaLabel: "الأكثر طلباً",
    ctaHref: "/contact",
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "scale",
    name: "توسّع",
    price: "حسب الطلب",
    period: "",
    description: "تطبيقات ويب ومنصات معقدة مع شراكة مستمرة.",
    features: ["نطاق مخصص", "فريق مخصص", "Retainer شهري", "SLA ودعم"],
    highlighted: false,
    ctaLabel: "تواصل معنا",
    ctaHref: "/contact",
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const FALLBACK_FAQS: FaqItem[] = [
  {
    id: "faq-1",
    question: "كم يستغرق المشروع عادةً؟",
    answer: "المواقع التسويقية: 2-4 أسابيع. تطبيقات الويب: 6-12 أسبوعاً حسب النطاق. نعمل بـ sprints أسبوعين مع عروض أسبوعية.",
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-2",
    question: "هل تعملون مع startups أو منظمات غير ربحية؟",
    answer: "نعم — نخصص مقاعد كل ربع سنة لمشاريع ذات أثر اجتماعي بأسعار مخفّضة. تواصل معنا وشاركنا قصتك.",
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-3",
    question: "ما التقنيات التي تستخدمونها؟",
    answer: "React، Next.js، TypeScript، Tailwind وFirebase. نختار stack مجرّب يبقى مدعوماً لسنوات.",
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-4",
    question: "هل تقدمون SEO ونمو مستمر؟",
    answer: "بالتأكيد — retainers شهرية للـ SEO وCRO والمحتوى. كثير من العملاء يبدأون ببناء ثم يتحولون لشراكة طويلة.",
    order: 4,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-5",
    question: "هل نستطيع إدارة المحتوى بأنفسنا؟",
    answer: "نعم. كل موقع نسلّمه جاهز لـ CMS مع لوحة تحكم نظيفة — فريقك يعدّل النصوص والصور بدون لمس الكود.",
    order: 5,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const FALLBACK_SITE_STATS: SiteStat[] = [
  {
    id: "stat-projects",
    value: "120+",
    label: "مشروع منجز",
    icon: "FolderCheck",
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "stat-satisfaction",
    value: "98%",
    label: "رضا العملاء",
    icon: "Heart",
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "stat-roi",
    value: "4.2×",
    label: "متوسط ROI",
    icon: "TrendingUp",
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "stat-awards",
    value: "12",
    label: "جائزة وتقدير",
    icon: "Trophy",
    order: 4,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const BLOG_CATEGORIES = [
  "الكل",
  "الأداء",
  "SEO",
  "UI/UX",
  "تصميم",
  "هندسة",
  "عمليات",
];

export function formatPostDate(iso: string): string {
  return new Date(iso).toLocaleDateString("ar-EG", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}
