import type {
  Author,
  BlogPost,
  FaqItem,
  Service,
  SiteStat,
  Testimonial,
} from "@/types/cms";
import { blogImage, serviceImage } from "@/lib/site-images";

const ts = "2026-06-01T00:00:00.000Z";

export const FALLBACK_SERVICES: Service[] = [
  {
    id: "web-design",
    slug: "web-design",
    title: "تصميم المواقع",
    tagline: "مواقع جميلة تحوّل الزوار لعملاء.",
    shortDescription: "مواقع تركّز على التحويل بتصميم راقٍ وحركة مدروسة.",
    description:
      "نصمّم مواقع تبدو احترافية، سريعة، وتحوّل الزوار إلى عملاء. كل تفصيلة مدروسة — من الشبكة إلى أصغر تفاعل.",
    icon: "Globe",
    features: ["تصميم متوافق مع الهوية", "تخطيطات متجاوبة", "حركة وتفاعلات", "تكامل CMS"],
    deliverables: [
      "تصميم بصري متوافق مع العلامة",
      "تخطيطات متجاوبة",
      "حركة وتفاعلات دقيقة",
      "تسليم نظام تصميم",
      "بنية جاهزة لـ CMS",
    ],
    imageUrl: serviceImage("web-design"),
    process: [
      { title: "اكتشاف", description: "ورش عمل، تحليل الجمهور والمنافسين." },
      { title: "تصميم", description: "Wireframes، شاشات عالية الدقة ونظام موثّق." },
      { title: "بناء", description: "كود جاهز للإنتاج مع أداء مدمج." },
      { title: "تحسين", description: "تحسين ما بعد الإطلاق بناءً على البيانات." },
    ],
    order: 1,
    status: "published",
    metaTitle: "تصميم المواقع — Top1Markting",
    metaDescription: "مواقع تركّز على التحويل بتصميم راقٍ وحركة مدروسة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "web-apps",
    slug: "web-apps",
    title: "تطبيقات الويب",
    tagline: "تطبيقات قابلة للتوسع. بنية نظيفة.",
    shortDescription: "تطبيقات ويب قابلة للتوسع بأحدث التقنيات وبنية نظيفة.",
    description:
      "من الأدوات الداخلية إلى المنصات الموجهة للعملاء — نبني تطبيقات تتوسع مع عملك وتبقى سهلة الصيانة.",
    icon: "Code2",
    features: ["React / Next.js", "واجهات برمجية آمنة", "صلاحيات ومستخدمين", "بنية Edge-ready"],
    deliverables: [
      "React / Next.js / TypeScript",
      "واجهات برمجية آمنة",
      "مصادقة وصلاحيات",
      "بنية Edge-ready",
      "اختبارات وCI/CD",
    ],
    imageUrl: serviceImage("web-apps"),
    process: [
      { title: "تخطيط", description: "البنية، نمذجة البيانات، تحديد النطاق." },
      { title: "تصميم", description: "مسارات المستخدم، نماذج أولية، نظام تصميم." },
      { title: "بناء", description: "Sprints أسبوعين مع عروض أسبوعية." },
      { title: "إطلاق", description: "نشر، مراقبة، تكرار." },
    ],
    order: 2,
    status: "published",
    metaTitle: "تطبيقات الويب — Top1Markting",
    metaDescription: "تطبيقات ويب قابلة للتوسع بأحدث التقنيات وبنية نظيفة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "seo",
    slug: "seo",
    title: "تحسين SEO",
    tagline: "نمو عضوي مُهندَس.",
    shortDescription: "SEO تقني، استراتيجية محتوى ونمو عضوي قابل للقياس.",
    description: "SEO تقني واستراتيجية محتوى ونمو قابل للقياس. نحوّل البحث إلى قناة اكتساب موثوقة.",
    icon: "Search",
    features: ["تدقيق تقني", "استراتيجية محتوى", "Schema markup", "تقارير شهرية"],
    deliverables: [
      "تدقيق تقني",
      "استراتيجية كلمات مفتاحية",
      "Schema markup",
      "استراتيجية روابط",
      "تقارير شهرية",
    ],
    imageUrl: serviceImage("seo"),
    process: [
      { title: "تدقيق", description: "فحص الموقع، تحديد العوائق والفرص السريعة." },
      { title: "استراتيجية", description: "Clusters كلمات مفتاحية وخارطة محتوى." },
      { title: "تنفيذ", description: "تحسينات On-page وتقنية ومحتوى." },
      { title: "قياس", description: "تقارير شهرية مرتبطة بالإيرادات." },
    ],
    order: 3,
    status: "published",
    metaTitle: "تحسين SEO — Top1Markting",
    metaDescription: "SEO تقني، استراتيجية محتوى ونمو عضوي قابل للقياس.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "ui-ux",
    slug: "ui-ux",
    title: "تصميم UI / UX",
    tagline: "واجهات يحبها المستخدمون.",
    shortDescription: "واجهات جميلة وبديهية مبنية على بحث المستخدم الحقيقي.",
    description:
      "تصميم مبني على البحث يجعل المنتجات المعقدة بسيطة. جميل، قابل للوصول، قابل للقياس.",
    icon: "Palette",
    features: ["بحث المستخدم", "أنظمة تصميم", "نماذج أولية", "إمكانية الوصول WCAG"],
    deliverables: [
      "بحث المستخدم",
      "هندسة المعلومات",
      "تصميم عالي الدقة",
      "نظام تصميم",
      "اختبار قابلية الاستخدام",
    ],
    imageUrl: serviceImage("ui-ux"),
    process: [
      { title: "بحث", description: "مقابلات، Jobs-to-be-done، تحليل المنافسين." },
      { title: "تصميم", description: "Wireframes، نماذج أولية، شاشات نهائية." },
      { title: "تحقق", description: "اختبار قابلية الاستخدام مع مستخدمين حقيقيين." },
      { title: "تسليم", description: "نظام موثّق جاهز للتطوير." },
    ],
    order: 4,
    status: "published",
    metaTitle: "تصميم UI / UX — Top1Markting",
    metaDescription: "واجهات جميلة وبديهية مبنية على بحث المستخدم الحقيقي.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "digital-solutions",
    slug: "digital-solutions",
    title: "حلول رقمية",
    tagline: "منصات مخصصة من البداية للنهاية.",
    shortDescription: "منصات مخصصة، أتمتة وتكاملات لعملك.",
    description: "نبني منصات مخصصة وأتمتة وتكاملات تربط عملك وتزيل الاحتكاك.",
    icon: "Layers",
    features: ["أدوات داخلية", "تكاملات API", "أتمتة", "ربط CRM وERP"],
    deliverables: [
      "أدوات داخلية",
      "تكاملات API",
      "أتمتة سير العمل",
      "ربط CRM وERP",
      "لوحات تحكم مخصصة",
    ],
    imageUrl: serviceImage("digital-solutions"),
    process: [
      { title: "اكتشاف", description: "رسم سير العمل ونقاط الألم." },
      { title: "تصميم", description: "بنية الحل وتجربة المستخدم." },
      { title: "بناء", description: "تسليم على مراحل." },
      { title: "دعم", description: "صيانة وتحسينات مستمرة." },
    ],
    order: 5,
    status: "published",
    metaTitle: "حلول رقمية — Top1Markting",
    metaDescription: "منصات مخصصة، أتمتة وتكاملات لعملك.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
];

const blogContent = `<h2>مقدمة</h2>
<p>هنا يبدأ المقال. في التطبيق الحقيقي، هذا المحتوى يُدار من لوحة التحكم — فريق التحرير ينشر بدون لمس الكود.</p>
<p>أسلوب Top1Markting: اكتب كأنك تشرح لصديق ذكي جديد على الموضوع.</p>
<h2>المشكلة الحقيقية</h2>
<p>كل مشروع يبدأ بسؤال: ما المشكلة الحقيقية التي نحلها؟ ليس العَرَض — السبب الجذري.</p>
<p>معظم الفرق تحسّن الشيء الخاطئ لأنها لم تتوقف لتسأل.</p>
<h2>منهجيتنا</h2>
<p>إطار من أربع خطوات: اكتشاف، تصميم، بناء، نمو. كل خطوة لها مخرجات واضحة وحلقة feedback.</p>
<h2>النتيجة</h2>
<p>عند التنفيذ الصحيح: منتج ينطلق بسرعة، يؤدي جيداً، ويستمر في النمو بعد الإطلاق.</p>
<h2>الخلاصة</h2>
<ul>
<li>ابدأ بالمشكلة الحقيقية، لا بالمطلوب السطحي.</li>
<li>الأداء قرار تصميم، ليس مرحلة أخيرة.</li>
<li>انشر بخطوات صغيرة قابلة للقياس.</li>
</ul>`;

export const FALLBACK_BLOG_POSTS: BlogPost[] = [
  {
    id: "lighthouse-99-by-default",
    slug: "lighthouse-99-by-default",
    title: "كيف نطلق مواقع Lighthouse 99 افتراضياً",
    excerpt: "الأداء ليس ميزة تُضاف في النهاية. هذا النظام الذي نستخدمه.",
    content: blogContent,
    featuredImage: blogImage("lighthouse-99-by-default"),
    featuredImageAlt: "شاشة تعرض نتائج أداء موقع ويب",
    category: "الأداء",
    tags: ["أداء", "lighthouse", "web-vitals"],
    author: "ليلى بناني",
    readTime: 6,
    views: 1240,
    trending: true,
    status: "published",
    metaTitle: "كيف نطلق مواقع Lighthouse 99 افتراضياً — Top1Markting",
    metaDescription: "الأداء ليس ميزة تُضاف في النهاية. هذا النظام الذي نستخدمه.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-06-12T00:00:00.000Z",
  },
  {
    id: "saas-seo-playbook-2026",
    slug: "saas-seo-playbook-2026",
    title: "دليل SEO عملي لشركات SaaS في 2026",
    excerpt: "انسَ الحيل. الدليل الذي ينجح في 2026 ممل، تقني، وبطيء — وهذا سره.",
    content: blogContent,
    featuredImage: blogImage("saas-seo-playbook-2026"),
    featuredImageAlt: "تحليل SEO على شاشة لابتوب",
    category: "SEO",
    tags: ["seo", "saas", "نمو"],
    author: "هناء صالح",
    readTime: 8,
    views: 980,
    trending: true,
    status: "published",
    metaTitle: "دليل SEO عملي لشركات SaaS في 2026 — Top1Markting",
    metaDescription: "انسَ الحيل. الدليل الذي ينجح في 2026 ممل، تقني، وبطيء.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-06-04T00:00:00.000Z",
  },
  {
    id: "premium-microinteractions",
    slug: "premium-microinteractions",
    title: "تصميم micro-interactions تبدو premium",
    excerpt: "لماذا المنتجات الأغلى ثمناً هي الأكثر restraint في الحركة.",
    content: blogContent,
    featuredImage: blogImage("premium-microinteractions"),
    featuredImageAlt: "تصميم واجهة مستخدم على شاشة",
    category: "UI/UX",
    tags: ["ui", "ux", "حركة"],
    author: "يوسف كرم",
    readTime: 5,
    views: 640,
    trending: false,
    status: "published",
    metaTitle: "تصميم micro-interactions تبدو premium — Top1Markting",
    metaDescription: "لماذا المنتجات الأغلى ثمناً هي الأكثر restraint في الحركة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-05-27T00:00:00.000Z",
  },
  {
    id: "design-system-foundations",
    slug: "design-system-foundations",
    title: "أساسيات نظام التصميم التي يجب أن تبدأ بها",
    excerpt: "قبل المكوّنات، قبل الـ tokens — الأساسيات التي تجعل النظام يتراكم.",
    content: blogContent,
    featuredImage: blogImage("design-system-foundations"),
    featuredImageAlt: "عينات ألوان وخطوط لنظام تصميم",
    category: "تصميم مواقع",
    tags: ["design-system", "tokens"],
    author: "عمر حديد",
    readTime: 7,
    views: 520,
    trending: false,
    status: "published",
    metaTitle: "أساسيات نظام التصميم — Top1Markting",
    metaDescription: "قبل المكوّنات، قبل الـ tokens — الأساسيات التي تجعل النظام يتراكم.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-05-18T00:00:00.000Z",
  },
  {
    id: "shipping-fast-without-debt",
    slug: "shipping-fast-without-debt",
    title: "الإطلاق السريع بدون تراكم tech debt",
    excerpt: "السرعة والجودة ليستا على طرفي نقيض إذا ضبطت الإعدادات الصحيحة.",
    content: blogContent,
    featuredImage: blogImage("shipping-fast-without-debt"),
    featuredImageAlt: "مطور يكتب كود على جهاز لابتوب",
    category: "هندسة",
    tags: ["هندسة", "tech-debt"],
    author: "ليلى بناني",
    readTime: 6,
    views: 410,
    trending: false,
    status: "published",
    metaTitle: "الإطلاق السريع بدون tech debt — Top1Markting",
    metaDescription: "السرعة والجودة ليستا على طرفي نقيض إذا ضبطت الإعدادات الصحيحة.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-05-03T00:00:00.000Z",
  },
  {
    id: "from-figma-to-production",
    slug: "from-figma-to-production",
    title: "من Figma للإنتاج — دليل التسليم",
    excerpt: "Checklist الدقيق الذي نستخدمه للانتقال من التصميم للكود بدون فقدان النية.",
    content: blogContent,
    featuredImage: blogImage("from-figma-to-production"),
    featuredImageAlt: "تصميم واجهة على شاشة ولوحة مفاتيح",
    category: "عمليات",
    tags: ["figma", "handoff", "عمليات"],
    author: "عمر حديد",
    readTime: 5,
    views: 380,
    trending: false,
    status: "published",
    metaTitle: "من Figma للإنتاج — Top1Markting",
    metaDescription: "Checklist الدقيق للانتقال من التصميم للكود بدون فقدان النية.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: "2026-04-22T00:00:00.000Z",
  },
];

export const FALLBACK_TESTIMONIALS: Testimonial[] = [
  {
    id: "t-vee",
    name: "الأستاذة دعاء محمد",
    role: "مالكة المتجر",
    company: "VEE",
    city: "القاهرة",
    quote:
      "تعامل احترافي من أول يوم لحد التسليم. الموقع بقى سريع وعصري وبيعكس ستايل البراند، والزبائن بقوا يطلبوا أسهل من الموبايل. تجربة الشغل مع توب ون كانت فوق الممتازة.",
    rating: 5,
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-al-general",
    name: "الأستاذ محمود رضا",
    role: "مدير العمليات",
    company: "الچينرال لتأجير السيارات",
    city: "دبي",
    quote:
      "الموقع صار يوضّح الأسطول والأسعار بشكل مرتب، والحجز صار أسهل بكثير. الفريق سريع في التعديلات وفاهمين سوق دبي كويس. أنصح فيهم لأي شركة تأجير.",
    rating: 5,
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-alforsan",
    name: "المهندس محروس الصياد",
    role: "مالك",
    company: "الفرسان للواجهات الزجاجية",
    city: "المنصورة",
    quote:
      "كنا محتاجين موقع يبان قد الشغل بتاعنا في الكلادينج والواجهات. عملولنا تصميم نظيف ومعرض مشاريع واضح، والناس بقت تتواصل من الموقع مباشرة. شغل محترم أوي.",
    rating: 5,
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-cutting-experts",
    name: "الأستاذ محمود نجيب",
    role: "مالك الشركة",
    company: "خبراء القص والتخريم",
    city: "الرياض",
    quote:
      "الموقع صار يعكس احترافية شغلنا في القص والتخريم. الاستفسارات زادت، والصفحة واضحة للعميل من أول دخول. تواصلهم سهل والتسليم على الوقت — ما قصروا معنا.",
    rating: 5,
    order: 4,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-malekcure",
    name: "الأستاذ رضا محمد",
    role: "مؤسس",
    company: "MalekCure",
    city: "جدة",
    quote:
      "من أول اجتماع حسينا إنهم فاهمين طبيعة خدماتنا. الموقع سريع، والتصميم يوصل ثقة للعميل الصناعي. بعد الإطلاق صارت الطلبات أوضح وأسهل تتبّعها.",
    rating: 5,
    order: 5,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-lunier",
    name: "الكابتن عبد الله الحربي",
    role: "مدير عام",
    company: "Lunier Marina",
    city: "دبي",
    quote:
      "أبغى موقع يعكس فخامة إدارة اليخوت، وهذا اللي صار. الواجهة راقية، والمحتوى مرتب، والعملاء يقدرون يفهمون الخدمات بدون تعقيد. شكراً لفريق توب ون.",
    rating: 5,
    order: 6,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-my-bag",
    name: "الأستاذة سلمى علاء",
    role: "صاحبة العلامة",
    company: "MY BAG",
    quote:
      "المتجر بقى شكله بريميوم والتصفح سهل جداً على الموبايل. الصور والحجز والطلب كله ماشي بسلاسة، والبنات بقوا يشاركوا اللينك. فرقت معايا كتير في المبيعات.",
    rating: 5,
    order: 7,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "t-vip-padel",
    name: "الأستاذ فهد الشمري",
    role: "مدير النادي",
    company: "VIP PADEL",
    city: "الرياض",
    quote:
      "نظام الحجز صار أوضح للعملاء، والملاعب تظهر بشكل مرتب. قبل كنا نضيع وقت على الواتساب، الحين أغلب الحجوزات من الموقع. شغل سريع ودعم ممتاز بعد الإطلاق.",
    rating: 5,
    order: 8,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const FALLBACK_FAQS: FaqItem[] = [
  {
    id: "faq-timeline",
    question: "كم يستغرق تصميم موقع أو متجر إلكتروني؟",
    answer:
      "الموقع التعريفي عادةً من ٢ إلى ٤ أسابيع. المتاجر الإلكترونية والمشاريع الأكبر من ٦ إلى ١٢ أسبوعاً حسب النطاق. نعمل بسبرنتات قصيرة مع تحديثات واضحة في كل مرحلة.",
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-markets",
    question: "هل تخدمون السعودية والإمارات فقط؟",
    answer:
      "لا، بنخدم أي عميل وفي أي دولة. تركيزنا وإعلاناتنا على السعودية والإمارات (الرياض، جدة، الدمام، القصيم، دبي، أبوظبي والشارقة)، ونبني مواقع لأي نشاط في أي مكان — مع دعم عربي كامل (RTL) وتجربة تناسب المستخدم المحلي.",
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-seo",
    question: "هل يشمل العمل تحسين محركات البحث SEO؟",
    answer:
      "نراعي SEO من البداية: بنية الصفحات، السرعة، Core Web Vitals، والبيانات المنظمة. ويمكن إضافة باقة شهرية لتحسين الظهور والمحتوى بعد الإطلاق.",
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-cms",
    question: "هل أقدر أعدّل المحتوى بنفسي بعد التسليم؟",
    answer:
      "نعم. نسلّم لوحة تحكم سهلة لتعديل النصوص والصور والمقالات بدون الحاجة لمطور في كل تغيير بسيط.",
    order: 4,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-pricing",
    question: "كيف يتم التسعير؟ وهل فيه عرض ثابت؟",
    answer:
      "التسعير يعتمد على نطاق المشروع (صفحات، متجر، تكاملات، SEO). بعد استشارة قصيرة نرسل عرضاً واضحاً بالمراحل والتكلفة قبل البدء — بدون مفاجآت.",
    order: 5,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-whatsapp",
    question: "كيف أتواصل معكم بسرعة؟",
    answer:
      "الأسرع عبر واتساب أو نموذج التواصل في الموقع. عادةً نرد خلال ٢٤ ساعة في أيام العمل، ونحدد موعد استشارة قصيرة لفهم احتياجك.",
    order: 6,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-hosting",
    question: "هل توفرون الاستضافة والنطاق؟",
    answer:
      "نساعد في اختيار الاستضافة المناسبة وربط النطاق، ونضبط الموقع ليكون سريعاً وآمناً. يمكن الاستضافة عندكم أو عبر مزوّد نقترحه حسب المشروع.",
    order: 7,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "faq-support",
    question: "ماذا بعد إطلاق الموقع؟ هل فيه دعم؟",
    answer:
      "بعد الإطلاق نقدّم فترة دعم للتعديلات الأساسية، ويمكن الاتفاق على صيانة شهرية للتحديثات، الأمان، والتحسين المستمر للأداء والـ SEO.",
    order: 8,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const FALLBACK_SITE_STATS: SiteStat[] = [
  {
    id: "stat-projects",
    value: "120+",
    label: "مشروع منجز",
    icon: "FolderCheck",
    order: 1,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "stat-satisfaction",
    value: "98%",
    label: "رضا العملاء",
    icon: "Heart",
    order: 2,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "stat-roi",
    value: "4.2×",
    label: "متوسط ROI",
    icon: "TrendingUp",
    order: 3,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "stat-awards",
    value: "12",
    label: "جائزة وتقدير",
    icon: "Trophy",
    order: 4,
    status: "published",
    createdAt: ts,
    updatedAt: ts,
  },
];

export const FALLBACK_AUTHORS: Author[] = [
  {
    id: "ahmed-refaei",
    slug: "ahmed-refaei",
    name: "أحمد الرفاعي",
    role: "مؤسس ومدير استراتيجي",
    bio: "يقود استراتيجية النمو الرقمي لـ Top1Markting في السعودية والإمارات — من تصميم المواقع حتى SEO والتسويق القابل للقياس. يركز على تحويل الزيارات إلى استفسارات وعملاء.",
    avatarUrl: "/authors/ahmed-refaei.png",
    expertise: ["استراتيجية رقمية", "SEO", "تصميم مواقع", "تحويل"],
    order: 1,
    status: "published",
    metaTitle: "أحمد الرفاعي | مؤسس Top1Markting",
    metaDescription:
      "ملف أحمد الرفاعي — مؤسس Top1Markting. خبرة في تصميم المواقع وSEO والتسويق الرقمي للسعودية والإمارات.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
  {
    id: "mohamed-al-khatib",
    slug: "mohamed-al-khatib",
    name: "محمد الخطيب",
    role: "مؤسس ومدير استراتيجي",
    bio: "شارك في تأسيس Top1Markting ويقود الرؤية الاستراتيجية للنمو في السعودية والإمارات — بناء عروض رقمية واضحة، وتحسين التحويل من البحث والإعلانات إلى عملاء حقيقيين.",
    avatarUrl: "/authors/mohamed-al-khatib.png",
    expertise: ["استراتيجية رقمية", "SEO", "تصميم مواقع", "تحويل"],
    order: 2,
    status: "published",
    metaTitle: "محمد الخطيب | مؤسس Top1Markting",
    metaDescription:
      "ملف محمد الخطيب — مؤسس ومدير استراتيجي في Top1Markting. خبرة في النمو الرقمي وتصميم المواقع وSEO للسعودية والإمارات.",
    createdAt: ts,
    updatedAt: ts,
    publishedAt: ts,
  },
];

export const BLOG_CATEGORIES = ["الكل", "الأداء", "SEO", "UI/UX", "تصميم", "هندسة", "عمليات"];

export function formatPostDate(iso: string): string {
  return new Date(iso).toLocaleDateString("ar-SA", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}
