/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DigitalMarketingRouteImport } from './routes/digital-marketing'
import { Route as EcommerceDevelopmentRouteImport } from './routes/ecommerce-development'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SeoBuraidahRouteImport } from './routes/seo-buraidah'
import { Route as SeoQassimRouteImport } from './routes/seo-qassim'
import { Route as SeoRiyadhRouteImport } from './routes/seo-riyadh'
import { Route as SeoServicesRouteImport } from './routes/seo-services'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WebDesignBuraidahRouteImport } from './routes/web-design-buraidah'
import { Route as WebDesignEgyptRouteImport } from './routes/web-design-egypt'
import { Route as WebDesignQassimRouteImport } from './routes/web-design-qassim'
import { Route as WebDesignRiyadhRouteImport } from './routes/web-design-riyadh'
import { Route as WebDesignSaudiArabiaRouteImport } from './routes/web-design-saudi-arabia'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminSeoAiRouteImport } from './routes/admin.seo-ai'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as ApiFirebaseConfigRouteImport } from './routes/api/firebase-config'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MediaIdRouteImport } from './routes/media.$id'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminFaqsIdRouteImport } from './routes/admin.faqs.$id'
import { Route as AdminPagesIdRouteImport } from './routes/admin.pages.$id'
import { Route as AdminPortfolioIdRouteImport } from './routes/admin.portfolio.$id'
import { Route as AdminPricingIdRouteImport } from './routes/admin.pricing.$id'
import { Route as AdminServicesIdRouteImport } from './routes/admin.services.$id'
import { Route as AdminStatsIdRouteImport } from './routes/admin.stats.$id'
import { Route as AdminTestimonialsIdRouteImport } from './routes/admin.testimonials.$id'
import { Route as ApiCmsResourceRouteImport } from './routes/api/cms.$resource'
import { Route as ApiSeoAnalyzeRouteImport } from './routes/api/seo.analyze'
import { Route as ApiSeoCreateDraftRouteImport } from './routes/api/seo.create-draft'
import { Route as ApiSeoGenerateDraftRouteImport } from './routes/api/seo.generate-draft'
import { Route as ApiSeoGenerateDraftsRouteImport } from './routes/api/seo.generate-drafts'
import { Route as ApiSeoGscRouteImport } from './routes/api/seo.gsc'
import { Route as ApiSeoHealthRouteImport } from './routes/api/seo.health'
import { Route as ApiSeoInsightsRouteImport } from './routes/api/seo.insights'
import { Route as ApiSeoLogsRouteImport } from './routes/api/seo.logs'
import { Route as ApiSeoGscCallbackRouteImport } from './routes/api/seo.gsc.callback'
import { Route as ApiSeoGscConnectRouteImport } from './routes/api/seo.gsc.connect'
import { Route as ApiSeoGscStatusRouteImport } from './routes/api/seo.gsc.status'
import { Route as ApiSeoGscSyncRouteImport } from './routes/api/seo.gsc.sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalMarketingRoute = DigitalMarketingRouteImport.update({
  id: '/digital-marketing',
  path: '/digital-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceDevelopmentRoute = EcommerceDevelopmentRouteImport.update({
  id: '/ecommerce-development',
  path: '/ecommerce-development',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoBuraidahRoute = SeoBuraidahRouteImport.update({
  id: '/seo-buraidah',
  path: '/seo-buraidah',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoQassimRoute = SeoQassimRouteImport.update({
  id: '/seo-qassim',
  path: '/seo-qassim',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRiyadhRoute = SeoRiyadhRouteImport.update({
  id: '/seo-riyadh',
  path: '/seo-riyadh',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesRoute = SeoServicesRouteImport.update({
  id: '/seo-services',
  path: '/seo-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignBuraidahRoute = WebDesignBuraidahRouteImport.update({
  id: '/web-design-buraidah',
  path: '/web-design-buraidah',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignEgyptRoute = WebDesignEgyptRouteImport.update({
  id: '/web-design-egypt',
  path: '/web-design-egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignQassimRoute = WebDesignQassimRouteImport.update({
  id: '/web-design-qassim',
  path: '/web-design-qassim',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignRiyadhRoute = WebDesignRiyadhRouteImport.update({
  id: '/web-design-riyadh',
  path: '/web-design-riyadh',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignSaudiArabiaRoute = WebDesignSaudiArabiaRouteImport.update({
  id: '/web-design-saudi-arabia',
  path: '/web-design-saudi-arabia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoAiRoute = AdminSeoAiRouteImport.update({
  id: '/seo-ai',
  path: '/seo-ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const ApiFirebaseConfigRoute = ApiFirebaseConfigRouteImport.update({
  id: '/api/firebase-config',
  path: '/api/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const MediaIdRoute = MediaIdRouteImport.update({
  id: '/media/$id',
  path: '/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminFaqsIdRoute = AdminFaqsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFaqsRoute,
} as any)
const AdminPagesIdRoute = AdminPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminPortfolioIdRoute = AdminPortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPortfolioRoute,
} as any)
const AdminPricingIdRoute = AdminPricingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPricingRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminStatsIdRoute = AdminStatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStatsRoute,
} as any)
const AdminTestimonialsIdRoute = AdminTestimonialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTestimonialsRoute,
} as any)
const ApiCmsResourceRoute = ApiCmsResourceRouteImport.update({
  id: '/api/cms/$resource',
  path: '/api/cms/$resource',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoAnalyzeRoute = ApiSeoAnalyzeRouteImport.update({
  id: '/api/seo/analyze',
  path: '/api/seo/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoCreateDraftRoute = ApiSeoCreateDraftRouteImport.update({
  id: '/api/seo/create-draft',
  path: '/api/seo/create-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoGenerateDraftRoute = ApiSeoGenerateDraftRouteImport.update({
  id: '/api/seo/generate-draft',
  path: '/api/seo/generate-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoGenerateDraftsRoute = ApiSeoGenerateDraftsRouteImport.update({
  id: '/api/seo/generate-drafts',
  path: '/api/seo/generate-drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoGscRoute = ApiSeoGscRouteImport.update({
  id: '/api/seo/gsc',
  path: '/api/seo/gsc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoHealthRoute = ApiSeoHealthRouteImport.update({
  id: '/api/seo/health',
  path: '/api/seo/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoInsightsRoute = ApiSeoInsightsRouteImport.update({
  id: '/api/seo/insights',
  path: '/api/seo/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoLogsRoute = ApiSeoLogsRouteImport.update({
  id: '/api/seo/logs',
  path: '/api/seo/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeoGscCallbackRoute = ApiSeoGscCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiSeoGscRoute,
} as any)
const ApiSeoGscConnectRoute = ApiSeoGscConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ApiSeoGscRoute,
} as any)
const ApiSeoGscStatusRoute = ApiSeoGscStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiSeoGscRoute,
} as any)
const ApiSeoGscSyncRoute = ApiSeoGscSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => ApiSeoGscRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/ecommerce-development': typeof EcommerceDevelopmentRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo-buraidah': typeof SeoBuraidahRoute
  '/seo-qassim': typeof SeoQassimRoute
  '/seo-riyadh': typeof SeoRiyadhRoute
  '/seo-services': typeof SeoServicesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/web-design-buraidah': typeof WebDesignBuraidahRoute
  '/web-design-egypt': typeof WebDesignEgyptRoute
  '/web-design-qassim': typeof WebDesignQassimRoute
  '/web-design-riyadh': typeof WebDesignRiyadhRoute
  '/web-design-saudi-arabia': typeof WebDesignSaudiArabiaRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/portfolio': typeof AdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/seo-ai': typeof AdminSeoAiRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/api/firebase-config': typeof ApiFirebaseConfigRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/media/$id': typeof MediaIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/cms/$resource': typeof ApiCmsResourceRoute
  '/api/seo/analyze': typeof ApiSeoAnalyzeRoute
  '/api/seo/create-draft': typeof ApiSeoCreateDraftRoute
  '/api/seo/generate-draft': typeof ApiSeoGenerateDraftRoute
  '/api/seo/generate-drafts': typeof ApiSeoGenerateDraftsRoute
  '/api/seo/gsc': typeof ApiSeoGscRouteWithChildren
  '/api/seo/health': typeof ApiSeoHealthRoute
  '/api/seo/insights': typeof ApiSeoInsightsRoute
  '/api/seo/logs': typeof ApiSeoLogsRoute
  '/api/seo/gsc/callback': typeof ApiSeoGscCallbackRoute
  '/api/seo/gsc/connect': typeof ApiSeoGscConnectRoute
  '/api/seo/gsc/status': typeof ApiSeoGscStatusRoute
  '/api/seo/gsc/sync': typeof ApiSeoGscSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/ecommerce-development': typeof EcommerceDevelopmentRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo-buraidah': typeof SeoBuraidahRoute
  '/seo-qassim': typeof SeoQassimRoute
  '/seo-riyadh': typeof SeoRiyadhRoute
  '/seo-services': typeof SeoServicesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/web-design-buraidah': typeof WebDesignBuraidahRoute
  '/web-design-egypt': typeof WebDesignEgyptRoute
  '/web-design-qassim': typeof WebDesignQassimRoute
  '/web-design-riyadh': typeof WebDesignRiyadhRoute
  '/web-design-saudi-arabia': typeof WebDesignSaudiArabiaRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/portfolio': typeof AdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/seo-ai': typeof AdminSeoAiRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/api/firebase-config': typeof ApiFirebaseConfigRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/media/$id': typeof MediaIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/cms/$resource': typeof ApiCmsResourceRoute
  '/api/seo/analyze': typeof ApiSeoAnalyzeRoute
  '/api/seo/create-draft': typeof ApiSeoCreateDraftRoute
  '/api/seo/generate-draft': typeof ApiSeoGenerateDraftRoute
  '/api/seo/generate-drafts': typeof ApiSeoGenerateDraftsRoute
  '/api/seo/gsc': typeof ApiSeoGscRouteWithChildren
  '/api/seo/health': typeof ApiSeoHealthRoute
  '/api/seo/insights': typeof ApiSeoInsightsRoute
  '/api/seo/logs': typeof ApiSeoLogsRoute
  '/api/seo/gsc/callback': typeof ApiSeoGscCallbackRoute
  '/api/seo/gsc/connect': typeof ApiSeoGscConnectRoute
  '/api/seo/gsc/status': typeof ApiSeoGscStatusRoute
  '/api/seo/gsc/sync': typeof ApiSeoGscSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/digital-marketing': typeof DigitalMarketingRoute
  '/ecommerce-development': typeof EcommerceDevelopmentRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/seo-buraidah': typeof SeoBuraidahRoute
  '/seo-qassim': typeof SeoQassimRoute
  '/seo-riyadh': typeof SeoRiyadhRoute
  '/seo-services': typeof SeoServicesRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/web-design-buraidah': typeof WebDesignBuraidahRoute
  '/web-design-egypt': typeof WebDesignEgyptRoute
  '/web-design-qassim': typeof WebDesignQassimRoute
  '/web-design-riyadh': typeof WebDesignRiyadhRoute
  '/web-design-saudi-arabia': typeof WebDesignSaudiArabiaRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/portfolio': typeof AdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/seo-ai': typeof AdminSeoAiRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/api/firebase-config': typeof ApiFirebaseConfigRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/media/$id': typeof MediaIdRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
  '/api/cms/$resource': typeof ApiCmsResourceRoute
  '/api/seo/analyze': typeof ApiSeoAnalyzeRoute
  '/api/seo/create-draft': typeof ApiSeoCreateDraftRoute
  '/api/seo/generate-draft': typeof ApiSeoGenerateDraftRoute
  '/api/seo/generate-drafts': typeof ApiSeoGenerateDraftsRoute
  '/api/seo/gsc': typeof ApiSeoGscRouteWithChildren
  '/api/seo/health': typeof ApiSeoHealthRoute
  '/api/seo/insights': typeof ApiSeoInsightsRoute
  '/api/seo/logs': typeof ApiSeoLogsRoute
  '/api/seo/gsc/callback': typeof ApiSeoGscCallbackRoute
  '/api/seo/gsc/connect': typeof ApiSeoGscConnectRoute
  '/api/seo/gsc/status': typeof ApiSeoGscStatusRoute
  '/api/seo/gsc/sync': typeof ApiSeoGscSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/digital-marketing'
    | '/ecommerce-development'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/seo-buraidah'
    | '/seo-qassim'
    | '/seo-riyadh'
    | '/seo-services'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/web-design-buraidah'
    | '/web-design-egypt'
    | '/web-design-qassim'
    | '/web-design-riyadh'
    | '/web-design-saudi-arabia'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/seo'
    | '/admin/seo-ai'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/api/firebase-config'
    | '/api/leads'
    | '/api/upload-image'
    | '/blog/$slug'
    | '/media/$id'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
    | '/api/cms/$resource'
    | '/api/seo/analyze'
    | '/api/seo/create-draft'
    | '/api/seo/generate-draft'
    | '/api/seo/generate-drafts'
    | '/api/seo/gsc'
    | '/api/seo/health'
    | '/api/seo/insights'
    | '/api/seo/logs'
    | '/api/seo/gsc/callback'
    | '/api/seo/gsc/connect'
    | '/api/seo/gsc/status'
    | '/api/seo/gsc/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/digital-marketing'
    | '/ecommerce-development'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/seo-buraidah'
    | '/seo-qassim'
    | '/seo-riyadh'
    | '/seo-services'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/web-design-buraidah'
    | '/web-design-egypt'
    | '/web-design-qassim'
    | '/web-design-riyadh'
    | '/web-design-saudi-arabia'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/seo'
    | '/admin/seo-ai'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/api/firebase-config'
    | '/api/leads'
    | '/api/upload-image'
    | '/blog/$slug'
    | '/media/$id'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
    | '/api/cms/$resource'
    | '/api/seo/analyze'
    | '/api/seo/create-draft'
    | '/api/seo/generate-draft'
    | '/api/seo/generate-drafts'
    | '/api/seo/gsc'
    | '/api/seo/health'
    | '/api/seo/insights'
    | '/api/seo/logs'
    | '/api/seo/gsc/callback'
    | '/api/seo/gsc/connect'
    | '/api/seo/gsc/status'
    | '/api/seo/gsc/sync'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/cookies'
    | '/digital-marketing'
    | '/ecommerce-development'
    | '/portfolio'
    | '/pricing'
    | '/privacy'
    | '/robots.txt'
    | '/seo-buraidah'
    | '/seo-qassim'
    | '/seo-riyadh'
    | '/seo-services'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/web-design-buraidah'
    | '/web-design-egypt'
    | '/web-design-qassim'
    | '/web-design-riyadh'
    | '/web-design-saudi-arabia'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/seo'
    | '/admin/seo-ai'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/api/firebase-config'
    | '/api/leads'
    | '/api/upload-image'
    | '/blog/$slug'
    | '/media/$id'
    | '/portfolio/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
    | '/api/cms/$resource'
    | '/api/seo/analyze'
    | '/api/seo/create-draft'
    | '/api/seo/generate-draft'
    | '/api/seo/generate-drafts'
    | '/api/seo/gsc'
    | '/api/seo/health'
    | '/api/seo/insights'
    | '/api/seo/logs'
    | '/api/seo/gsc/callback'
    | '/api/seo/gsc/connect'
    | '/api/seo/gsc/status'
    | '/api/seo/gsc/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DigitalMarketingRoute: typeof DigitalMarketingRoute
  EcommerceDevelopmentRoute: typeof EcommerceDevelopmentRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SeoBuraidahRoute: typeof SeoBuraidahRoute
  SeoQassimRoute: typeof SeoQassimRoute
  SeoRiyadhRoute: typeof SeoRiyadhRoute
  SeoServicesRoute: typeof SeoServicesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WebDesignBuraidahRoute: typeof WebDesignBuraidahRoute
  WebDesignEgyptRoute: typeof WebDesignEgyptRoute
  WebDesignQassimRoute: typeof WebDesignQassimRoute
  WebDesignRiyadhRoute: typeof WebDesignRiyadhRoute
  WebDesignSaudiArabiaRoute: typeof WebDesignSaudiArabiaRoute
  ApiFirebaseConfigRoute: typeof ApiFirebaseConfigRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
  MediaIdRoute: typeof MediaIdRoute
  ApiCmsResourceRoute: typeof ApiCmsResourceRoute
  ApiSeoAnalyzeRoute: typeof ApiSeoAnalyzeRoute
  ApiSeoCreateDraftRoute: typeof ApiSeoCreateDraftRoute
  ApiSeoGenerateDraftRoute: typeof ApiSeoGenerateDraftRoute
  ApiSeoGenerateDraftsRoute: typeof ApiSeoGenerateDraftsRoute
  ApiSeoGscRoute: typeof ApiSeoGscRouteWithChildren
  ApiSeoHealthRoute: typeof ApiSeoHealthRoute
  ApiSeoInsightsRoute: typeof ApiSeoInsightsRoute
  ApiSeoLogsRoute: typeof ApiSeoLogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-marketing': {
      id: '/digital-marketing'
      path: '/digital-marketing'
      fullPath: '/digital-marketing'
      preLoaderRoute: typeof DigitalMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-development': {
      id: '/ecommerce-development'
      path: '/ecommerce-development'
      fullPath: '/ecommerce-development'
      preLoaderRoute: typeof EcommerceDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-buraidah': {
      id: '/seo-buraidah'
      path: '/seo-buraidah'
      fullPath: '/seo-buraidah'
      preLoaderRoute: typeof SeoBuraidahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-qassim': {
      id: '/seo-qassim'
      path: '/seo-qassim'
      fullPath: '/seo-qassim'
      preLoaderRoute: typeof SeoQassimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-riyadh': {
      id: '/seo-riyadh'
      path: '/seo-riyadh'
      fullPath: '/seo-riyadh'
      preLoaderRoute: typeof SeoRiyadhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services': {
      id: '/seo-services'
      path: '/seo-services'
      fullPath: '/seo-services'
      preLoaderRoute: typeof SeoServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-buraidah': {
      id: '/web-design-buraidah'
      path: '/web-design-buraidah'
      fullPath: '/web-design-buraidah'
      preLoaderRoute: typeof WebDesignBuraidahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-egypt': {
      id: '/web-design-egypt'
      path: '/web-design-egypt'
      fullPath: '/web-design-egypt'
      preLoaderRoute: typeof WebDesignEgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-qassim': {
      id: '/web-design-qassim'
      path: '/web-design-qassim'
      fullPath: '/web-design-qassim'
      preLoaderRoute: typeof WebDesignQassimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-riyadh': {
      id: '/web-design-riyadh'
      path: '/web-design-riyadh'
      fullPath: '/web-design-riyadh'
      preLoaderRoute: typeof WebDesignRiyadhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design-saudi-arabia': {
      id: '/web-design-saudi-arabia'
      path: '/web-design-saudi-arabia'
      fullPath: '/web-design-saudi-arabia'
      preLoaderRoute: typeof WebDesignSaudiArabiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo-ai': {
      id: '/admin/seo-ai'
      path: '/seo-ai'
      fullPath: '/admin/seo-ai'
      preLoaderRoute: typeof AdminSeoAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/firebase-config': {
      id: '/api/firebase-config'
      path: '/api/firebase-config'
      fullPath: '/api/firebase-config'
      preLoaderRoute: typeof ApiFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/media/$id': {
      id: '/media/$id'
      path: '/media/$id'
      fullPath: '/media/$id'
      preLoaderRoute: typeof MediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/faqs/$id': {
      id: '/admin/faqs/$id'
      path: '/$id'
      fullPath: '/admin/faqs/$id'
      preLoaderRoute: typeof AdminFaqsIdRouteImport
      parentRoute: typeof AdminFaqsRoute
    }
    '/admin/pages/$id': {
      id: '/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminPagesIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/portfolio/$id': {
      id: '/admin/portfolio/$id'
      path: '/$id'
      fullPath: '/admin/portfolio/$id'
      preLoaderRoute: typeof AdminPortfolioIdRouteImport
      parentRoute: typeof AdminPortfolioRoute
    }
    '/admin/pricing/$id': {
      id: '/admin/pricing/$id'
      path: '/$id'
      fullPath: '/admin/pricing/$id'
      preLoaderRoute: typeof AdminPricingIdRouteImport
      parentRoute: typeof AdminPricingRoute
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/stats/$id': {
      id: '/admin/stats/$id'
      path: '/$id'
      fullPath: '/admin/stats/$id'
      preLoaderRoute: typeof AdminStatsIdRouteImport
      parentRoute: typeof AdminStatsRoute
    }
    '/admin/testimonials/$id': {
      id: '/admin/testimonials/$id'
      path: '/$id'
      fullPath: '/admin/testimonials/$id'
      preLoaderRoute: typeof AdminTestimonialsIdRouteImport
      parentRoute: typeof AdminTestimonialsRoute
    }
    '/api/cms/$resource': {
      id: '/api/cms/$resource'
      path: '/api/cms/$resource'
      fullPath: '/api/cms/$resource'
      preLoaderRoute: typeof ApiCmsResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/analyze': {
      id: '/api/seo/analyze'
      path: '/api/seo/analyze'
      fullPath: '/api/seo/analyze'
      preLoaderRoute: typeof ApiSeoAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/create-draft': {
      id: '/api/seo/create-draft'
      path: '/api/seo/create-draft'
      fullPath: '/api/seo/create-draft'
      preLoaderRoute: typeof ApiSeoCreateDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/generate-draft': {
      id: '/api/seo/generate-draft'
      path: '/api/seo/generate-draft'
      fullPath: '/api/seo/generate-draft'
      preLoaderRoute: typeof ApiSeoGenerateDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/generate-drafts': {
      id: '/api/seo/generate-drafts'
      path: '/api/seo/generate-drafts'
      fullPath: '/api/seo/generate-drafts'
      preLoaderRoute: typeof ApiSeoGenerateDraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/gsc': {
      id: '/api/seo/gsc'
      path: '/api/seo/gsc'
      fullPath: '/api/seo/gsc'
      preLoaderRoute: typeof ApiSeoGscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/health': {
      id: '/api/seo/health'
      path: '/api/seo/health'
      fullPath: '/api/seo/health'
      preLoaderRoute: typeof ApiSeoHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/insights': {
      id: '/api/seo/insights'
      path: '/api/seo/insights'
      fullPath: '/api/seo/insights'
      preLoaderRoute: typeof ApiSeoInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/logs': {
      id: '/api/seo/logs'
      path: '/api/seo/logs'
      fullPath: '/api/seo/logs'
      preLoaderRoute: typeof ApiSeoLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seo/gsc/callback': {
      id: '/api/seo/gsc/callback'
      path: '/callback'
      fullPath: '/api/seo/gsc/callback'
      preLoaderRoute: typeof ApiSeoGscCallbackRouteImport
      parentRoute: typeof ApiSeoGscRoute
    }
    '/api/seo/gsc/connect': {
      id: '/api/seo/gsc/connect'
      path: '/connect'
      fullPath: '/api/seo/gsc/connect'
      preLoaderRoute: typeof ApiSeoGscConnectRouteImport
      parentRoute: typeof ApiSeoGscRoute
    }
    '/api/seo/gsc/status': {
      id: '/api/seo/gsc/status'
      path: '/status'
      fullPath: '/api/seo/gsc/status'
      preLoaderRoute: typeof ApiSeoGscStatusRouteImport
      parentRoute: typeof ApiSeoGscRoute
    }
    '/api/seo/gsc/sync': {
      id: '/api/seo/gsc/sync'
      path: '/sync'
      fullPath: '/api/seo/gsc/sync'
      preLoaderRoute: typeof ApiSeoGscSyncRouteImport
      parentRoute: typeof ApiSeoGscRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminFaqsRouteChildren {
  AdminFaqsIdRoute: typeof AdminFaqsIdRoute
}

const AdminFaqsRouteChildren: AdminFaqsRouteChildren = {
  AdminFaqsIdRoute: AdminFaqsIdRoute,
}

const AdminFaqsRouteWithChildren = AdminFaqsRoute._addFileChildren(
  AdminFaqsRouteChildren,
)

interface AdminPagesRouteChildren {
  AdminPagesIdRoute: typeof AdminPagesIdRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesIdRoute: AdminPagesIdRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminPortfolioRouteChildren {
  AdminPortfolioIdRoute: typeof AdminPortfolioIdRoute
}

const AdminPortfolioRouteChildren: AdminPortfolioRouteChildren = {
  AdminPortfolioIdRoute: AdminPortfolioIdRoute,
}

const AdminPortfolioRouteWithChildren = AdminPortfolioRoute._addFileChildren(
  AdminPortfolioRouteChildren,
)

interface AdminPricingRouteChildren {
  AdminPricingIdRoute: typeof AdminPricingIdRoute
}

const AdminPricingRouteChildren: AdminPricingRouteChildren = {
  AdminPricingIdRoute: AdminPricingIdRoute,
}

const AdminPricingRouteWithChildren = AdminPricingRoute._addFileChildren(
  AdminPricingRouteChildren,
)

interface AdminServicesRouteChildren {
  AdminServicesIdRoute: typeof AdminServicesIdRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesIdRoute: AdminServicesIdRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminStatsRouteChildren {
  AdminStatsIdRoute: typeof AdminStatsIdRoute
}

const AdminStatsRouteChildren: AdminStatsRouteChildren = {
  AdminStatsIdRoute: AdminStatsIdRoute,
}

const AdminStatsRouteWithChildren = AdminStatsRoute._addFileChildren(
  AdminStatsRouteChildren,
)

interface AdminTestimonialsRouteChildren {
  AdminTestimonialsIdRoute: typeof AdminTestimonialsIdRoute
}

const AdminTestimonialsRouteChildren: AdminTestimonialsRouteChildren = {
  AdminTestimonialsIdRoute: AdminTestimonialsIdRoute,
}

const AdminTestimonialsRouteWithChildren =
  AdminTestimonialsRoute._addFileChildren(AdminTestimonialsRouteChildren)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminFaqsRoute: typeof AdminFaqsRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPortfolioRoute: typeof AdminPortfolioRouteWithChildren
  AdminPricingRoute: typeof AdminPricingRouteWithChildren
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSeoAiRoute: typeof AdminSeoAiRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRouteWithChildren
  AdminTestimonialsRoute: typeof AdminTestimonialsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminFaqsRoute: AdminFaqsRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPortfolioRoute: AdminPortfolioRouteWithChildren,
  AdminPricingRoute: AdminPricingRouteWithChildren,
  AdminSeoRoute: AdminSeoRoute,
  AdminSeoAiRoute: AdminSeoAiRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRouteWithChildren,
  AdminTestimonialsRoute: AdminTestimonialsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ApiSeoGscRouteChildren {
  ApiSeoGscCallbackRoute: typeof ApiSeoGscCallbackRoute
  ApiSeoGscConnectRoute: typeof ApiSeoGscConnectRoute
  ApiSeoGscStatusRoute: typeof ApiSeoGscStatusRoute
  ApiSeoGscSyncRoute: typeof ApiSeoGscSyncRoute
}

const ApiSeoGscRouteChildren: ApiSeoGscRouteChildren = {
  ApiSeoGscCallbackRoute: ApiSeoGscCallbackRoute,
  ApiSeoGscConnectRoute: ApiSeoGscConnectRoute,
  ApiSeoGscStatusRoute: ApiSeoGscStatusRoute,
  ApiSeoGscSyncRoute: ApiSeoGscSyncRoute,
}

const ApiSeoGscRouteWithChildren = ApiSeoGscRoute._addFileChildren(
  ApiSeoGscRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DigitalMarketingRoute: DigitalMarketingRoute,
  EcommerceDevelopmentRoute: EcommerceDevelopmentRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SeoBuraidahRoute: SeoBuraidahRoute,
  SeoQassimRoute: SeoQassimRoute,
  SeoRiyadhRoute: SeoRiyadhRoute,
  SeoServicesRoute: SeoServicesRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WebDesignBuraidahRoute: WebDesignBuraidahRoute,
  WebDesignEgyptRoute: WebDesignEgyptRoute,
  WebDesignQassimRoute: WebDesignQassimRoute,
  WebDesignRiyadhRoute: WebDesignRiyadhRoute,
  WebDesignSaudiArabiaRoute: WebDesignSaudiArabiaRoute,
  ApiFirebaseConfigRoute: ApiFirebaseConfigRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
  MediaIdRoute: MediaIdRoute,
  ApiCmsResourceRoute: ApiCmsResourceRoute,
  ApiSeoAnalyzeRoute: ApiSeoAnalyzeRoute,
  ApiSeoCreateDraftRoute: ApiSeoCreateDraftRoute,
  ApiSeoGenerateDraftRoute: ApiSeoGenerateDraftRoute,
  ApiSeoGenerateDraftsRoute: ApiSeoGenerateDraftsRoute,
  ApiSeoGscRoute: ApiSeoGscRouteWithChildren,
  ApiSeoHealthRoute: ApiSeoHealthRoute,
  ApiSeoInsightsRoute: ApiSeoInsightsRoute,
  ApiSeoLogsRoute: ApiSeoLogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
