/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload-image'
import { Route as ApiFirebaseConfigRouteImport } from './routes/api/firebase-config'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminStatsRouteImport } from './routes/admin.stats'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminTestimonialsIdRouteImport } from './routes/admin.testimonials.$id'
import { Route as AdminStatsIdRouteImport } from './routes/admin.stats.$id'
import { Route as AdminServicesIdRouteImport } from './routes/admin.services.$id'
import { Route as AdminPricingIdRouteImport } from './routes/admin.pricing.$id'
import { Route as AdminPortfolioIdRouteImport } from './routes/admin.portfolio.$id'
import { Route as AdminPagesIdRouteImport } from './routes/admin.pages.$id'
import { Route as AdminFaqsIdRouteImport } from './routes/admin.faqs.$id'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload-image',
  path: '/api/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFirebaseConfigRoute = ApiFirebaseConfigRouteImport.update({
  id: '/api/firebase-config',
  path: '/api/firebase-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsIdRoute = AdminTestimonialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTestimonialsRoute,
} as any)
const AdminStatsIdRoute = AdminStatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminStatsRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminPricingIdRoute = AdminPricingIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPricingRoute,
} as any)
const AdminPortfolioIdRoute = AdminPortfolioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPortfolioRoute,
} as any)
const AdminPagesIdRoute = AdminPagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPagesRoute,
} as any)
const AdminFaqsIdRoute = AdminFaqsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFaqsRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/portfolio': typeof AdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/api/firebase-config': typeof ApiFirebaseConfigRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/portfolio': typeof AdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/api/firebase-config': typeof ApiFirebaseConfigRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/faqs': typeof AdminFaqsRouteWithChildren
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRouteWithChildren
  '/admin/portfolio': typeof AdminPortfolioRouteWithChildren
  '/admin/pricing': typeof AdminPricingRouteWithChildren
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stats': typeof AdminStatsRouteWithChildren
  '/admin/testimonials': typeof AdminTestimonialsRouteWithChildren
  '/api/firebase-config': typeof ApiFirebaseConfigRoute
  '/api/upload-image': typeof ApiUploadImageRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/faqs/$id': typeof AdminFaqsIdRoute
  '/admin/pages/$id': typeof AdminPagesIdRoute
  '/admin/portfolio/$id': typeof AdminPortfolioIdRoute
  '/admin/pricing/$id': typeof AdminPricingIdRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/stats/$id': typeof AdminStatsIdRoute
  '/admin/testimonials/$id': typeof AdminTestimonialsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/api/firebase-config'
    | '/api/upload-image'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/api/firebase-config'
    | '/api/upload-image'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/services'
    | '/sitemap.xml'
    | '/admin/blog'
    | '/admin/faqs'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/portfolio'
    | '/admin/pricing'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/stats'
    | '/admin/testimonials'
    | '/api/firebase-config'
    | '/api/upload-image'
    | '/blog/$slug'
    | '/services/$slug'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/faqs/$id'
    | '/admin/pages/$id'
    | '/admin/portfolio/$id'
    | '/admin/pricing/$id'
    | '/admin/services/$id'
    | '/admin/stats/$id'
    | '/admin/testimonials/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiFirebaseConfigRoute: typeof ApiFirebaseConfigRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/upload-image': {
      id: '/api/upload-image'
      path: '/api/upload-image'
      fullPath: '/api/upload-image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/firebase-config': {
      id: '/api/firebase-config'
      path: '/api/firebase-config'
      fullPath: '/api/firebase-config'
      preLoaderRoute: typeof ApiFirebaseConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials/$id': {
      id: '/admin/testimonials/$id'
      path: '/$id'
      fullPath: '/admin/testimonials/$id'
      preLoaderRoute: typeof AdminTestimonialsIdRouteImport
      parentRoute: typeof AdminTestimonialsRoute
    }
    '/admin/stats/$id': {
      id: '/admin/stats/$id'
      path: '/$id'
      fullPath: '/admin/stats/$id'
      preLoaderRoute: typeof AdminStatsIdRouteImport
      parentRoute: typeof AdminStatsRoute
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/pricing/$id': {
      id: '/admin/pricing/$id'
      path: '/$id'
      fullPath: '/admin/pricing/$id'
      preLoaderRoute: typeof AdminPricingIdRouteImport
      parentRoute: typeof AdminPricingRoute
    }
    '/admin/portfolio/$id': {
      id: '/admin/portfolio/$id'
      path: '/$id'
      fullPath: '/admin/portfolio/$id'
      preLoaderRoute: typeof AdminPortfolioIdRouteImport
      parentRoute: typeof AdminPortfolioRoute
    }
    '/admin/pages/$id': {
      id: '/admin/pages/$id'
      path: '/$id'
      fullPath: '/admin/pages/$id'
      preLoaderRoute: typeof AdminPagesIdRouteImport
      parentRoute: typeof AdminPagesRoute
    }
    '/admin/faqs/$id': {
      id: '/admin/faqs/$id'
      path: '/$id'
      fullPath: '/admin/faqs/$id'
      preLoaderRoute: typeof AdminFaqsIdRouteImport
      parentRoute: typeof AdminFaqsRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
  }
}

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminFaqsRouteChildren {
  AdminFaqsIdRoute: typeof AdminFaqsIdRoute
}

const AdminFaqsRouteChildren: AdminFaqsRouteChildren = {
  AdminFaqsIdRoute: AdminFaqsIdRoute,
}

const AdminFaqsRouteWithChildren = AdminFaqsRoute._addFileChildren(
  AdminFaqsRouteChildren,
)

interface AdminPagesRouteChildren {
  AdminPagesIdRoute: typeof AdminPagesIdRoute
}

const AdminPagesRouteChildren: AdminPagesRouteChildren = {
  AdminPagesIdRoute: AdminPagesIdRoute,
}

const AdminPagesRouteWithChildren = AdminPagesRoute._addFileChildren(
  AdminPagesRouteChildren,
)

interface AdminPortfolioRouteChildren {
  AdminPortfolioIdRoute: typeof AdminPortfolioIdRoute
}

const AdminPortfolioRouteChildren: AdminPortfolioRouteChildren = {
  AdminPortfolioIdRoute: AdminPortfolioIdRoute,
}

const AdminPortfolioRouteWithChildren = AdminPortfolioRoute._addFileChildren(
  AdminPortfolioRouteChildren,
)

interface AdminPricingRouteChildren {
  AdminPricingIdRoute: typeof AdminPricingIdRoute
}

const AdminPricingRouteChildren: AdminPricingRouteChildren = {
  AdminPricingIdRoute: AdminPricingIdRoute,
}

const AdminPricingRouteWithChildren = AdminPricingRoute._addFileChildren(
  AdminPricingRouteChildren,
)

interface AdminServicesRouteChildren {
  AdminServicesIdRoute: typeof AdminServicesIdRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesIdRoute: AdminServicesIdRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminStatsRouteChildren {
  AdminStatsIdRoute: typeof AdminStatsIdRoute
}

const AdminStatsRouteChildren: AdminStatsRouteChildren = {
  AdminStatsIdRoute: AdminStatsIdRoute,
}

const AdminStatsRouteWithChildren = AdminStatsRoute._addFileChildren(
  AdminStatsRouteChildren,
)

interface AdminTestimonialsRouteChildren {
  AdminTestimonialsIdRoute: typeof AdminTestimonialsIdRoute
}

const AdminTestimonialsRouteChildren: AdminTestimonialsRouteChildren = {
  AdminTestimonialsIdRoute: AdminTestimonialsIdRoute,
}

const AdminTestimonialsRouteWithChildren =
  AdminTestimonialsRoute._addFileChildren(AdminTestimonialsRouteChildren)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminFaqsRoute: typeof AdminFaqsRouteWithChildren
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagesRoute: typeof AdminPagesRouteWithChildren
  AdminPortfolioRoute: typeof AdminPortfolioRouteWithChildren
  AdminPricingRoute: typeof AdminPricingRouteWithChildren
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStatsRoute: typeof AdminStatsRouteWithChildren
  AdminTestimonialsRoute: typeof AdminTestimonialsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminFaqsRoute: AdminFaqsRouteWithChildren,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagesRoute: AdminPagesRouteWithChildren,
  AdminPortfolioRoute: AdminPortfolioRouteWithChildren,
  AdminPricingRoute: AdminPricingRouteWithChildren,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStatsRoute: AdminStatsRouteWithChildren,
  AdminTestimonialsRoute: AdminTestimonialsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiFirebaseConfigRoute: ApiFirebaseConfigRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
